import type { Metadata } from 'next';
import { Italiana, Julius_Sans_One, Nunito_Sans } from 'next/font/google';
import './globals.css';
// import SocketApp from './socketApp';

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
});

export const juliusSansOne = Julius_Sans_One({
  variable: '--font-julius-sans-one',
  weight: '400',
  subsets: ['latin'],
});

export const italiana = Italiana({
  variable: '--font-italiana',
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className} antialiased`}>{children}</body>
      {/* <SocketApp/> */}
    </html>
  );
}
